import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navbar from "../components/Navbar";
import Card from "../components/Card";
import data from "../components/data";
export default function Home() {
	const cards = data.map(card => {
		return (
			<Card
				key={card.id}
				upCountry={card.country.toUpperCase()}
				{...card}
			/>
		);
	});
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>

				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<main className={styles.main}>
				{cards}
			</main>
		</div>
	);
}
